apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: portall-ace-mq
  name: portall-ace-mq
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: portall-ace-mq
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: portall-ace-mq
    spec:
      containers:
      - env:
        - name: LICENSE
          value: accept
        - name: MQSI_PERSISTENT_MONITORING_EVENTS
          value: "1"
        - name: MQ_QMGR_NAME
          value: PCS_UAT_QMG
        image: docker-registry.uat.ipanlpm.com:5000/ace-mq:v6 <change image name>
        imagePullPolicy: IfNotPresent
        name: portall-ace-mq
        ports:
        - containerPort: 7600
          protocol: TCP
        - containerPort: 1414
          protocol: TCP
        - containerPort: 7800
          protocol: TCP
        - containerPort: 7843
          protocol: TCP
        - containerPort: 9157
          protocol: TCP
        - containerPort: 9443
          protocol: TCP
        - containerPort: 9483
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/aceuser/build
          name: aceuser
        - mountPath: /home/aceuser/ace-server/log
          name: volume-1
        - mountPath: /home/aceuser/ace-server/run
          name: volume-2
        - mountPath: /home/aceuser/ace-server/overrides
          name: volume-3
        - mountPath: /home/aceuser/ace-server/shared-classes
          name: volume-4
        - mountPath: /mnt/mqm2
          name: volume-5
        - mountPath: /opt/ibm/ace-11/server/ODBC/unixodbc/odbc.ini
          name: volume-7
          subPath: odbc.ini
      dnsPolicy: ClusterFirst
      hostname: portall-ace-mq
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: aceuser
        persistentVolumeClaim:
          claimName: ace1
      - name: volume-1
        persistentVolumeClaim:
          claimName: ace2
      - name: volume-2
        persistentVolumeClaim:
          claimName: ace3
      - name: volume-3
        persistentVolumeClaim:
          claimName: ace4
      - name: volume-4
        persistentVolumeClaim:
          claimName: ace5
      - name: volume-5
        persistentVolumeClaim:
          claimName: ace6
      - configMap:
          name: odbc
        name: volume-6
